version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: techvify-landing
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - techvify-network

networks:
  techvify-network:
    driver: bridge